# Generated by Django 4.2.4 on 2023-10-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_name', models.CharField(max_length=100)),
                ('vm_status', models.TextField()),
                ('is_started', models.BooleanField(default=False)),
                ('is_compiled', models.BooleanField(default=False)),
                ('is_downloaded', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('is_running', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=False)),
                ('param_name', models.CharField(max_length=100)),
                ('param_value', models.CharField(max_length=100)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
    ]
