# Generated by Django 4.2.4 on 2023-11-24 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_delete_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PyTerminal',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='VM',
        ),
    ]
