# Generated by Django 4.2.4 on 2024-01-08 11:30

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0003_delete_pyterminal_delete_user_delete_vm'),
    ]

    operations = [
        migrations.CreateModel(
            name='VBControllerInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('serialized_controller', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
    ]
