# Generated by Django 4.2.4 on 2023-10-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_user_username_alter_vm_param_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PyTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_py_open', models.BooleanField(default=False)),
                ('current_command', models.CharField(blank=True, max_length=100, null=True)),
                ('all_commands', models.TextField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='vm',
            name='vm_status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
