# Generated by Django 4.2.4 on 2023-10-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_pyterminal_alter_vm_vm_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyterminal',
            name='terminal_name',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
