# Generated by Django 4.2.4 on 2023-11-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_scripts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyscript',
            name='script_status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
