# Generated by Django 4.2.4 on 2023-11-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_scripts', '0003_pyscript_script_is_executed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyscript',
            name='script_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
