# Generated by Django 4.2.4 on 2023-11-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_machines', '0002_rename_is_compiled_vm_connection_is_online_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vm',
            name='param_value',
            field=models.CharField(blank=True, default='1337', max_length=100, null=True),
        ),
    ]
