# Generated by Django 4.2.4 on 2023-11-28 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_machines', '0003_alter_vm_param_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.CharField(blank=True, max_length=100, null=True)),
                ('param_type', models.CharField(choices=[('Bool', 'Bool'), ('Int', 'Int'), ('Real', 'Real'), ('String', 'String')], default='Int', max_length=100)),
                ('param_value', models.CharField(blank=True, default='1337', max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vm',
            name='param_name',
        ),
        migrations.RemoveField(
            model_name='vm',
            name='param_type',
        ),
        migrations.RemoveField(
            model_name='vm',
            name='param_value',
        ),
        migrations.AddField(
            model_name='vm',
            name='param',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='virtual_machines.param'),
        ),
    ]
