# Generated by Django 4.2.4 on 2023-11-28 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_machines', '0004_param_remove_vm_param_name_remove_vm_param_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vm',
            name='name_of_previous_selected_program',
        ),
        migrations.RemoveField(
            model_name='vm',
            name='param',
        ),
        migrations.RemoveField(
            model_name='vm',
            name='param_is_read',
        ),
        migrations.RemoveField(
            model_name='vm',
            name='param_is_written',
        ),
        migrations.RemoveField(
            model_name='vm',
            name='path_to_previous_selected_program',
        ),
        migrations.RemoveField(
            model_name='vm',
            name='vm_previous_name',
        ),
        migrations.DeleteModel(
            name='Param',
        ),
    ]
