# Generated by Django 4.2.4 on 2024-02-20 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_machines', '0006_vm_message_what_changed_last'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('device_type', models.CharField(choices=[('CMMT-AS-MP', 'CMMT-AS-MP'), ('CMMT-ST-MP', 'CMMT-ST-MP')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, unique=True)),
                ('project_path', models.CharField(max_length=100, unique=True)),
                ('git_hash', models.CharField(max_length=100, unique=True)),
                ('topology_type', models.PositiveIntegerField()),
                ('devices_in_the_topology', models.ManyToManyField(blank=True, null=True, related_name='projects', to='virtual_machines.device')),
            ],
        ),
        migrations.CreateModel(
            name='Plc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plc_name', models.CharField(max_length=100, unique=True)),
                ('plc_type', models.CharField(choices=[('Beckhoff', 'Beckhoff'), ('Siemens', 'Siemens'), ('Festo', 'Festo'), ('Rockwell', 'Rockwell')], max_length=100)),
                ('ams_net_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('version', models.CharField(max_length=100)),
                ('loaded_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plcs', to='virtual_machines.project')),
            ],
        ),
    ]
