# Generated by Django 4.2.4 on 2024-03-05 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_machines', '0010_plc_vendor_name_alter_plc_plc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='selected_plc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vms', to='virtual_machines.plc'),
        ),
    ]
