# Generated by Django 4.2.4 on 2024-03-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_machines', '0011_vm_selected_plc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='topology_type',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
