# Generated by Django 4.2.4 on 2024-03-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_machines', '0014_alter_project_topology_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='topology_type',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
