# Generated by Django 4.2.4 on 2024-03-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_machines', '0015_alter_project_topology_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='sequence_is_initiated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vm',
            name='message_what_changed_last',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='vm',
            name='vm_type',
            field=models.CharField(choices=[('TwinCAT', 'TwinCAT'), ('TiaPortal', 'TiaPortal'), ('Codesys', 'Codesys'), ('Studio5000', 'Studio5000')], default='TwinCAT', max_length=100, unique=True),
        ),
    ]
